#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${ROOT_DIR:-$(pwd)}"
SOURCE_CSV="${SOURCE_CSV:-data/processed/sequence_cluster_split_all_raw/pdbbind_sequence_cluster_splits.csv}"
SPLIT_DIR="${SPLIT_DIR:-str/split_sequence_cluster_all_raw}"
MANIFEST_DIR="${MANIFEST_DIR:-str/manifest}"
LIGAND_PARSE_LIMIT="${LIGAND_PARSE_LIMIT:--1}"

MANIFEST_CSV="${MANIFEST_CSV:-${MANIFEST_DIR}/esm_affinity_manifest.csv}"
MANIFEST_REPORT="${MANIFEST_REPORT:-${MANIFEST_DIR}/esm_affinity_manifest_report.json}"
MANIFEST_VALIDATION_REPORT="${MANIFEST_VALIDATION_REPORT:-${MANIFEST_DIR}/esm_affinity_manifest_validation_report.json}"
INTERFORMER_CSV="${INTERFORMER_CSV:-${MANIFEST_DIR}/general_PL_2020_sequence_cluster_all_raw.csv}"
TRAINABLE_CSV="${TRAINABLE_CSV:-${MANIFEST_DIR}/esm_affinity_trainable_manifest.csv}"
LIGAND_FAILURES_CSV="${LIGAND_FAILURES_CSV:-${MANIFEST_DIR}/ligand_parse_failures.csv}"
TRAINABLE_REPORT="${TRAINABLE_REPORT:-${MANIFEST_DIR}/esm_affinity_trainable_manifest_report.json}"

cd "${ROOT_DIR}"
export PYTHONPATH="${ROOT_DIR}${PYTHONPATH:+:${PYTHONPATH}}"

echo "Build manifest pipeline"
echo "ROOT_DIR=${ROOT_DIR}"
echo "SOURCE_CSV=${SOURCE_CSV}"
echo "SPLIT_DIR=${SPLIT_DIR}"
echo "MANIFEST_DIR=${MANIFEST_DIR}"
echo "LIGAND_PARSE_LIMIT=${LIGAND_PARSE_LIMIT}"
echo

CURRENT_STAGE="initialization"
trap 'echo "[FAIL] ${CURRENT_STAGE}" >&2' ERR

require_path() {
  local path="$1"
  local message="$2"
  if [[ ! -e "${path}" ]]; then
    echo "Missing ${message}: ${path}" >&2
    exit 1
  fi
}

require_path "${SOURCE_CSV}" "source CSV generated by scripts/create_sequence_cluster_split.py"
require_path "${SPLIT_DIR}/timesplit_no_lig_overlap_train" "train split file"
require_path "${SPLIT_DIR}/timesplit_no_lig_overlap_val" "valid split file"
require_path "${SPLIT_DIR}/timesplit_test" "test split file"

mkdir -p "${MANIFEST_DIR}"

run_stage() {
  local stage="$1"
  shift
  CURRENT_STAGE="${stage}"
  local start_time
  start_time="$(date +%s)"
  echo "[START] ${stage}"
  "$@"
  local end_time
  end_time="$(date +%s)"
  echo "[DONE] ${stage} ($((end_time - start_time))s)"
  echo
}

run_stage "[1/4] Build full ESM affinity manifest" \
  python str/scripts/data/create_esm_manifest.py \
    --source-csv "${SOURCE_CSV}" \
    --split-dir "${SPLIT_DIR}" \
    --output-csv "${MANIFEST_CSV}" \
    --report-json "${MANIFEST_REPORT}" \
    --interformer-csv "${INTERFORMER_CSV}"

run_stage "[2/4] Validate manifest paths, labels, sequences, and split membership" \
  python str/scripts/data/validate_manifest.py \
    --manifest "${MANIFEST_CSV}" \
    --report-json "${MANIFEST_VALIDATION_REPORT}" \
    --split-dir "${SPLIT_DIR}" \
    --ligand-parse-limit "${LIGAND_PARSE_LIMIT}"

run_stage "[3/4] Create trainable manifest by filtering unparseable ligands" \
  python str/scripts/data/create_trainable_manifest.py \
    --manifest "${MANIFEST_CSV}" \
    --output-csv "${TRAINABLE_CSV}" \
    --failures-csv "${LIGAND_FAILURES_CSV}" \
    --report-json "${TRAINABLE_REPORT}"

CURRENT_STAGE="[4/4] Summary"
echo "[START] ${CURRENT_STAGE}"
python - "${MANIFEST_CSV}" "${MANIFEST_REPORT}" "${MANIFEST_VALIDATION_REPORT}" "${TRAINABLE_CSV}" "${TRAINABLE_REPORT}" "${LIGAND_FAILURES_CSV}" <<'PY'
import json
import sys
from pathlib import Path

paths = {
    "manifest": Path(sys.argv[1]),
    "manifest_report": Path(sys.argv[2]),
    "validation_report": Path(sys.argv[3]),
    "trainable_manifest": Path(sys.argv[4]),
    "trainable_report": Path(sys.argv[5]),
    "ligand_failures": Path(sys.argv[6]),
}
for name, path in paths.items():
    print(f"{name}: {path} ({'exists' if path.exists() else 'missing'})")

report_path = paths["trainable_report"]
if report_path.exists():
    report = json.loads(report_path.read_text())
    print(json.dumps(report.get("summary", report), indent=2, ensure_ascii=False))
PY
echo "[DONE] ${CURRENT_STAGE}"
echo

echo "Done."
