#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${ROOT_DIR:-$(pwd)}"
MANIFEST="${MANIFEST:-str/manifest/esm_affinity_manifest.csv}"
TRAINABLE_MANIFEST="${TRAINABLE_MANIFEST:-str/manifest/esm_affinity_trainable_manifest.csv}"
SPLIT_DIR="${SPLIT_DIR:-str/split_sequence_cluster_all_raw}"

MANIFEST_VALIDATION_REPORT="${MANIFEST_VALIDATION_REPORT:-str/manifest/esm_affinity_manifest_validation_report.json}"
TRAINABLE_REPORT="${TRAINABLE_REPORT:-str/manifest/esm_affinity_trainable_manifest_report.json}"
LIGAND_FAILURES_CSV="${LIGAND_FAILURES_CSV:-str/manifest/ligand_parse_failures.csv}"

LIGAND_CACHE_DIR="${LIGAND_CACHE_DIR:-str/manifest/cache/ligand_graphs}"
LIGAND_CACHE_REPORT="${LIGAND_CACHE_REPORT:-str/manifest/cache/ligand_graphs_report.json}"
LIGAND_CACHE_LIMIT="${LIGAND_CACHE_LIMIT:--1}"
LIGAND_OVERWRITE="${LIGAND_OVERWRITE:-0}"

ESM_CACHE_DIR="${ESM_CACHE_DIR:-str/manifest/cache/esm_embeddings}"
ESM_CACHE_REPORT="${ESM_CACHE_REPORT:-str/manifest/cache/esm_embeddings_report.json}"
ESM_MODEL_NAME="${ESM_MODEL_NAME:-facebook/esm2_t6_8M_UR50D}"
ESM_DEVICE="${ESM_DEVICE:-auto}"
ESM_LIMIT="${ESM_LIMIT:--1}"
ESM_CHUNK_BATCH_SIZE="${ESM_CHUNK_BATCH_SIZE:-4}"
ESM_MAX_RESIDUES_PER_CHUNK="${ESM_MAX_RESIDUES_PER_CHUNK:-1022}"
ESM_FLOAT16_OUTPUT="${ESM_FLOAT16_OUTPUT:-1}"
ESM_OVERWRITE="${ESM_OVERWRITE:-0}"
ESM_LOCAL_FILES_ONLY="${ESM_LOCAL_FILES_ONLY:-0}"

BATCH_SPLIT="${BATCH_SPLIT:-train}"
BATCH_LIMIT="${BATCH_LIMIT:-128}"
BATCH_SIZE="${BATCH_SIZE:-8}"
GRAPH_BATCH_REPORT="${GRAPH_BATCH_REPORT:-str/manifest/esm_affinity_graph_batch_smoke_report.json}"
BATCH_REPORT="${BATCH_REPORT:-str/manifest/esm_ligand_training_batch_report.json}"

cd "${ROOT_DIR}"
export PYTHONPATH="${ROOT_DIR}${PYTHONPATH:+:${PYTHONPATH}}"

echo "Validate after manifest pipeline"
echo "ROOT_DIR=${ROOT_DIR}"
echo "MANIFEST=${MANIFEST}"
echo "TRAINABLE_MANIFEST=${TRAINABLE_MANIFEST}"
echo "SPLIT_DIR=${SPLIT_DIR}"
echo "LIGAND_CACHE_DIR=${LIGAND_CACHE_DIR}"
echo "ESM_CACHE_DIR=${ESM_CACHE_DIR}"
echo "ESM_MODEL_NAME=${ESM_MODEL_NAME}"
echo "ESM_DEVICE=${ESM_DEVICE}"
echo "ESM_LIMIT=${ESM_LIMIT}"
echo "BATCH_SPLIT=${BATCH_SPLIT}"
echo "BATCH_LIMIT=${BATCH_LIMIT}"
echo "BATCH_SIZE=${BATCH_SIZE}"
echo

CURRENT_STAGE="initialization"
trap 'echo "[FAIL] ${CURRENT_STAGE}" >&2' ERR

require_path() {
  local path="$1"
  local message="$2"
  if [[ ! -e "${path}" ]]; then
    echo "Missing ${message}: ${path}" >&2
    exit 1
  fi
}

run_stage() {
  local stage="$1"
  shift
  CURRENT_STAGE="${stage}"
  local start_time
  start_time="$(date +%s)"
  echo "[START] ${stage}"
  "$@"
  local end_time
  end_time="$(date +%s)"
  echo "[DONE] ${stage} ($((end_time - start_time))s)"
  echo
}

require_path "${MANIFEST}" "manifest generated by build_manifest_from_split.sh"
require_path "${SPLIT_DIR}/timesplit_no_lig_overlap_train" "train split file"
require_path "${SPLIT_DIR}/timesplit_no_lig_overlap_val" "valid split file"
require_path "${SPLIT_DIR}/timesplit_test" "test split file"

run_stage "[1/6] Validate full manifest paths, labels, sequences, and splits" \
  python str/scripts/data/validate_manifest.py \
    --manifest "${MANIFEST}" \
    --report-json "${MANIFEST_VALIDATION_REPORT}" \
    --split-dir "${SPLIT_DIR}" \
    --ligand-parse-limit -1

run_stage "[2/6] Create trainable manifest by filtering unparseable ligands" \
  python str/scripts/data/create_trainable_manifest.py \
    --manifest "${MANIFEST}" \
    --output-csv "${TRAINABLE_MANIFEST}" \
    --failures-csv "${LIGAND_FAILURES_CSV}" \
    --report-json "${TRAINABLE_REPORT}"

ligand_args=(
  --manifest "${TRAINABLE_MANIFEST}"
  --cache-dir "${LIGAND_CACHE_DIR}"
  --report-json "${LIGAND_CACHE_REPORT}"
  --limit "${LIGAND_CACHE_LIMIT}"
)
if [[ "${LIGAND_OVERWRITE}" == "1" ]]; then
  ligand_args+=(--overwrite)
fi
run_stage "[3/6] Cache RDKit ligand graph tensors" \
  python str/scripts/data/cache_ligand_graphs.py "${ligand_args[@]}"

esm_args=(
  --manifest "${TRAINABLE_MANIFEST}"
  --cache-dir "${ESM_CACHE_DIR}"
  --report-json "${ESM_CACHE_REPORT}"
  --model-name "${ESM_MODEL_NAME}"
  --device "${ESM_DEVICE}"
  --limit "${ESM_LIMIT}"
  --chunk-batch-size "${ESM_CHUNK_BATCH_SIZE}"
  --max-residues-per-chunk "${ESM_MAX_RESIDUES_PER_CHUNK}"
)
if [[ "${ESM_FLOAT16_OUTPUT}" == "1" ]]; then
  esm_args+=(--float16-output)
fi
if [[ "${ESM_OVERWRITE}" == "1" ]]; then
  esm_args+=(--overwrite)
fi
if [[ "${ESM_LOCAL_FILES_ONLY}" == "1" ]]; then
  esm_args+=(--local-files-only)
fi
run_stage "[4/6] Cache frozen ESM residue embeddings" \
  python str/scripts/data/cache_esm_embeddings.py "${esm_args[@]}"

run_stage "[5/6] Smoke test ligand graph batch" \
  python str/scripts/data/smoke_test_graph_batch.py \
    --manifest "${TRAINABLE_MANIFEST}" \
    --cache-dir "${LIGAND_CACHE_DIR}" \
    --report-json "${GRAPH_BATCH_REPORT}" \
    --split "${BATCH_SPLIT}" \
    --batch-size "${BATCH_SIZE}"

run_stage "[6/6] Validate ESM + ligand training batch" \
  python str/scripts/data/build_training_batch.py \
    --manifest "${TRAINABLE_MANIFEST}" \
    --esm-cache-dir "${ESM_CACHE_DIR}" \
    --ligand-cache-dir "${LIGAND_CACHE_DIR}" \
    --report-json "${BATCH_REPORT}" \
    --split "${BATCH_SPLIT}" \
    --limit "${BATCH_LIMIT}" \
    --batch-size "${BATCH_SIZE}"

echo "All manifest-to-batch validation stages completed."
